import csv

APP_CASES = [
    ('APP-001', 'Login with valid credentials', 'Open the app, enter valid email and password, tap Sign In.', 'Sign In should succeed and Home screen should appear.', ''),
    ('APP-002', 'Login with invalid password', 'Enter valid email and invalid password, tap Sign In.', 'Error message should display and login should fail.', ''),
    ('APP-003', 'Navigate to Register from Login', 'Tap Register on the login screen.', 'Register screen should open.', ''),
    ('APP-004', 'Register new user with valid details', 'Fill Name, Email, Phone, Location, Password, verify OTP, then Create Account.', 'App should create account and navigate to Home screen.', ''),
    ('APP-005', 'Send OTP during registration', 'Enter valid email on register screen and tap Verify.', 'OTP dialog or confirmation should appear and OTP should be sent.', ''),
    ('APP-006', 'Verify valid OTP during registration', 'Enter OTP 1234 and confirm.', 'Email verification should succeed and UI should update.', ''),
    ('APP-007', 'Fail registration with mismatching OTP', 'Enter wrong OTP after sending it.', 'Invalid OTP error should display.', ''),
    ('APP-008', 'Prevent registration without email verification', 'Fill all fields but do not verify email and tap Create Account.', 'Create Account button should be disabled or registration should be blocked.', ''),
    ('APP-009', 'Show error for invalid email on login', 'Enter invalid email format and attempt to login.', 'Validation should show "Enter valid email".', ''),
    ('APP-010', 'Show error for short password on login', 'Enter password shorter than 6 chars and tap Sign In.', 'Validation should show "Min 6 characters".', ''),
    ('APP-011', 'Home screen displays bottom navigation', 'Login and verify Home screen navigation rail appears.', 'Bottom nav should show Dashboard, Scan, History, AgroBot, Profile.', ''),
    ('APP-012', 'Navigate to Dashboard tab', 'Tap Dashboard icon in bottom nav.', 'Dashboard screen should become active.', ''),
    ('APP-013', 'Navigate to Scan tab', 'Tap Scan icon in bottom nav.', 'Scan screen should become active.', ''),
    ('APP-014', 'Navigate to History tab', 'Tap History icon in bottom nav.', 'History screen should become active.', ''),
    ('APP-015', 'Navigate to AgroBot tab', 'Tap AgroBot icon in bottom nav.', 'Chatbot screen should become active.', ''),
    ('APP-016', 'Navigate to Profile tab', 'Tap Profile icon in bottom nav.', 'Profile screen should become active.', ''),
    ('APP-017', 'Open Scan screen camera picker', 'On Scan screen tap Camera button.', 'Camera intent/picker should open.', ''),
    ('APP-018', 'Open Scan screen gallery picker', 'On Scan screen tap Gallery button.', 'Gallery picker should open.', ''),
    ('APP-019', 'Select crop type dropdown', 'Tap dropdown and choose Tomato.', 'Selected crop should update to Tomato.', ''),
    ('APP-020', 'Analyze with no image selected', 'Tap Analyze button without image.', 'App should either block action or show warning.', ''),
    ('APP-021', 'Analyze after selecting gallery image', 'Choose gallery image and tap Analyze.', 'Result screen should open and analysis should proceed.', ''),
    ('APP-022', 'Analyze after taking photo', 'Take a camera photo and tap Analyze.', 'Result screen should open and image is processed.', ''),
    ('APP-023', 'Detect crop auto-detect flow', 'Select Auto-detect and pick image.', 'Crop should be identified automatically and shown on the screen.', ''),
    ('APP-024', 'Result screen displays disease name', 'Complete scan and wait for result screen.', 'Disease name should display in app bar title.', ''),
    ('APP-025', 'Result page shows severity badge', 'Open a completed result screen.', 'Severity badge with color should appear.', ''),
    ('APP-026', 'Result page shows treatment recommendations', 'Scroll result screen down.', 'Treatment section should show a list of remedies.', ''),
    ('APP-027', 'Result page shows prevention guidelines', 'Scroll to prevention section.', 'Prevention info should be visible.', ''),
    ('APP-028', 'History screen lists prior scans', 'Navigate to History from bottom nav.', 'Scan history list should appear or empty state if none.', ''),
    ('APP-029', 'Open history item detail', 'Tap on a history card.', 'Result screen should open for that history item.', ''),
    ('APP-030', 'History empty state message', 'Use fresh account with no scans.', 'No scan history yet message should appear.', ''),
    ('APP-031', 'Chatbot initial greeting appears', 'Go to AgroBot tab.', 'Welcome message should appear from AgroBot.', ''),
    ('APP-032', 'Send text question in chatbot', 'Enter text question and send.', 'Response should appear from AgroBot.', ''),
    ('APP-033', 'Tap a suggestion chip in chatbot', 'Tap one suggested query.', 'Query should be sent and response displayed.', ''),
    ('APP-034', 'Use mic icon to start voice input', 'Tap microphone icon on AgroBot.', 'Speech-to-text capture should begin or prompt should appear.', ''),
    ('APP-035', 'Text-to-speech response playback', 'Tap volume icon on chat app bar.', 'AgroBot should speak the latest response.', ''),
    ('APP-036', 'Dashboard quick action Scan button', 'On Dashboard tap Scan quick action.', 'App should navigate to Scan screen.', ''),
    ('APP-037', 'Dashboard quick action AgroBot button', 'On Dashboard tap AgroBot quick action.', 'App should navigate to Chatbot screen.', ''),
    ('APP-038', 'Dashboard quick action History button', 'On Dashboard tap History quick action.', 'App should navigate to History screen.', ''),
    ('APP-039', 'Dashboard quick action Weather button', 'On Dashboard tap Weather quick action.', 'App should navigate to Weather screen.', ''),
    ('APP-040', 'Weather screen loads location weather', 'Open Weather from Dashboard.', 'Weather screen should show weather data or fallback message.', ''),
    ('APP-041', 'Profile screen shows user details', 'Go to Profile tab.', 'Name, email, phone and location should display.', ''),
    ('APP-042', 'Profile screen update button opens editor', 'Tap Update Profile Info.', 'Edit bottom sheet should open.', ''),
    ('APP-043', 'Logout flow from profile', 'Tap logout and confirm.', 'User should return to Login screen.', ''),
    ('APP-044', 'Language switch to Hindi', 'Change language from profile or dashboard menu.', 'App text should update to Hindi on supported strings.', ''),
    ('APP-045', 'Login invalid email format error', 'Enter missing @ email and login.', 'Validation error should appear.', ''),
    ('APP-046', 'Registration missing required field error', 'Leave Name blank and tap Create Account.', 'Required field error should show.', ''),
    ('APP-047', 'Profile crop list display', 'On Profile screen view main crops.', 'Main Crops value should be shown or Not defined.', ''),
    ('APP-048', 'Home navigation retains selected tab', 'Switch tabs and return to Home.', 'Selected tab should remain until changed.', ''),
    ('APP-049', 'Back navigation from Scan', 'Press back on Scan.', 'App should navigate to previous screen or Home tab.', ''),
    ('APP-050', 'Permission request for location', 'Open Register and tap location picker.', 'Location permission prompt should appear if not granted.', ''),
    ('APP-051', 'Gallery permission request', 'Tap Gallery on Scan screen when permissions denied.', 'Permission request should appear or error handled.', ''),
    ('APP-052', 'Button disabled while loading', 'Trigger OTP send or login loading.', 'Button should show spinner and disable taps.', ''),
    ('APP-053', 'Verify demo OTP flow', 'Send OTP and enter 1234.', 'OTP should verify and registration continues.', ''),
    ('APP-054', 'App starts at splash screen', 'Launch app from cold start.', 'Splash screen should appear then login or home.', ''),
    ('APP-055', 'Scan screen shows detection tips', 'Open Scan screen.', 'Tips card should display camera guidance.', ''),
    ('APP-056', 'Result screen shows weather note block', 'Generate a result with weather note.', 'Weather note section should show if available.', ''),
    ('APP-057', 'History card shows timestamp', 'View history list.', 'Each history card should show date/time or details.', ''),
    ('APP-058', 'Dashboard shows field insights', 'Open Dashboard.', 'Field insights summary should display crop health ratio.', ''),
    ('APP-059', 'Dashboard animated quick actions', 'Open Dashboard.', 'Quick actions should animate in.', ''),
    ('APP-060', 'Register phone number validation', 'Enter invalid phone and attempt registration.', 'Validation should show required or invalid input.', ''),
    ('APP-061', 'Change password visibility toggle', 'Tap eye icon on login password.', 'Password text should toggle visible/invisible.', ''),
    ('APP-062', 'Registration location autofill', 'Tap current location icon on register.', 'Location field should auto-populate with city/district.', ''),
    ('APP-063', 'Handle missing Firebase data gracefully', 'Use account with no farmer document.', 'Profile should still show default values.', ''),
    ('APP-064', 'Chatbot send button on keyboard', 'Type question and press Enter.', 'Message should send and appear.', ''),
    ('APP-065', 'Dashboard language menu selection', 'Change language via dashboard language menu.', 'Locale should switch accordingly.', ''),
    ('APP-066', 'Weather quick action card tap', 'Tap weather card on Dashboard.', 'Weather screen opens.', ''),
    ('APP-067', 'Settings not found fallback', 'Open Profile or app with missing fields.', 'App should not crash if data missing.', ''),
    ('APP-068', 'Result screen loading placeholder', 'Start scan and view Result screen before results.', 'Loading UI should show until analysis complete.', ''),
    ('APP-069', 'Chatbot response error handling', 'Send question while network is off.', 'Error message should display and app should remain stable.', ''),
    ('APP-070', 'History item opens correct disease screen', 'Tap history item.', 'Result screen loads with that history details.', ''),
    ('APP-071', 'Verify Firebase login failure path', 'Login with non-existent credentials.', 'Login failed message should display.', ''),
    ('APP-072', 'Profile logout confirmation cancel', 'Open logout and select Cancel.', 'User should remain on Profile screen.', ''),
    ('APP-073', 'Dashboard greet displays farmer name', 'Open Dashboard after login.', 'Greeting should show user name from Firestore.', ''),
    ('APP-074', 'Register should handle web location fallback', 'Run on web and tap location icon.', 'Location should fill using OpenStreetMap fallback or coordinates.', ''),
    ('APP-075', 'History stream updates after scan', 'Complete a scan then go to History.', 'New scan should appear in history list.', ''),
    ('APP-076', 'Use chat suggestion before manual input', 'Tap one suggestion chip.', 'Chat should send and response should appear.', ''),
    ('APP-077', 'Profile bottom action button visible', 'Open Profile screen.', 'Update Profile Info button should appear.', ''),
    ('APP-078', 'Result screen supports back navigation', 'On Result screen tap back.', 'App should return to Scan screen or previous view.', ''),
    ('APP-079', 'Dashboard quick action grid visible', 'Open Dashboard.', 'Four quick action cards should be visible.', ''),
    ('APP-080', 'Registration form scrolls on small screens', 'Open registration on small device.', 'Form should scroll and fields remain accessible.', ''),
    ('APP-081', 'History empty card illustration', 'History with no scans.', 'Empty state graphic or text should show.', ''),
    ('APP-082', 'Scan image preview updates after selecting image', 'Select camera or gallery photo.', 'Preview container should show the image.', ''),
    ('APP-083', 'Chatbot voice button stops recording', 'Tap mic twice.', 'Voice recording should stop and transcript should populate.', ''),
    ('APP-084', 'Dashboard app bar language button works', 'Tap language icon on Dashboard.', 'Language menu should open.', ''),
    ('APP-085', 'Result page disease description visible', 'View result screen content.', 'Disease description paragraph should appear.', ''),
    ('APP-086', 'Scan analysis continues if result screen is visible', 'Start analyze and leave result screen open.', 'Result should update live without crash.', ''),
    ('APP-087', 'Verification OTP button disabled after send', 'Tap Verify email, then inspect button.', 'Verify button should change state to Sent or disable.', ''),
    ('APP-088', 'Register account should navigate home on success', 'Complete register flow.', 'App should navigate to Home screen.', ''),
    ('APP-089', 'Profile main crops list scrolls if long', 'Open Profile with many crops.', 'Crop list should wrap or scroll.', ''),
    ('APP-090', 'App remains stable when GPS denied', 'Deny location on Register or Weather.', 'App should show error and not crash.', ''),
    ('APP-091', 'Weather fallback demo mode handling', 'Open Weather with invalid API key.', 'Weather screen should show demo data or message.', ''),
    ('APP-092', 'History card tap opens result details', 'Tap an existing history item.', 'Result screen opens with details.', ''),
    ('APP-093', 'Chatbot shows typing/loading indicator', 'Send message to AgroBot.', 'Loading indicator should appear until response.', ''),
    ('APP-094', 'Profile edit sheet dismisses', 'Open edit profile sheet and tap outside.', 'Sheet should dismiss.', ''),
    ('APP-095', 'Login screen shows welcome header', 'Open login screen.', 'Welcome message should be visible.', ''),
    ('APP-096', 'Register screen shows hint text for OTP', 'Open register and send OTP.', 'Hint text should show 1234 for demo.', ''),
    ('APP-097', 'Scan crop selector list contains known crops', 'Open dropdown on Scan.', 'Crop list includes Rice, Wheat, Tomato.', ''),
    ('APP-098', 'Result page handles empty recommendations', 'Value available from result service with no treatments.', 'Page should still display gracefully.', ''),
    ('APP-099', 'Profile logout navigates to login', 'Confirm logout.', 'Login screen should show after logout.', ''),
    ('APP-100', 'Dashboard quick actions respond to taps', 'Tap each quick action card.', 'App should navigate to corresponding screen.', ''),
]

WEB_CASES = [
    ('WEB-001', 'Web login with valid credentials', 'Open web app, enter valid email and password, click Sign In.', 'Login should succeed and Home screen should appear.', ''),
    ('WEB-002', 'Web login invalid password', 'Enter valid email and wrong password, click Sign In.', 'Error message should display.', ''),
    ('WEB-003', 'Navigate to Register page', 'Click Register link on login page.', 'Register page should open.', ''),
    ('WEB-004', 'Register new user with valid details', 'Fill form fields, verify OTP, and submit.', 'New account should be created and redirected to Home.', ''),
    ('WEB-005', 'Send OTP during web registration', 'Enter valid email and click Verify.', 'OTP notification should display.', ''),
    ('WEB-006', 'Verify OTP using demo code', 'Enter 1234 and confirm.', 'Email verification should succeed.', ''),
    ('WEB-007', 'Registration blocks without OTP', 'Fill form but skip OTP verification.', 'Submit should be blocked or show validation.', ''),
    ('WEB-008', 'Password strength validation', 'Enter password under 6 chars.', 'Validation should show error.', ''),
    ('WEB-009', 'Access dashboard after login', 'Complete login flow.', 'Dashboard page should load.', ''),
    ('WEB-010', 'Web navigation tabs visible', 'View Home screen after login.', 'Dashboard, Scan, History, AgroBot, Profile tabs should show.', ''),
    ('WEB-011', 'Navigate to Scan section', 'Click Scan tab.', 'Scan section should display.', ''),
    ('WEB-012', 'Navigate to History section', 'Click History tab.', 'History timeline should show.', ''),
    ('WEB-013', 'Navigate to AgroBot section', 'Click AgroBot tab.', 'Chatbot UI should show.', ''),
    ('WEB-014', 'Navigate to Profile section', 'Click Profile tab.', 'Profile details should show.', ''),
    ('WEB-015', 'Upload leaf image from web', 'Use file picker to upload image on Scan page.', 'Image preview should display and upload succeed.', ''),
    ('WEB-016', 'Select crop type on web', 'Choose crop from dropdown.', 'Selected crop should update.', ''),
    ('WEB-017', 'Run analysis after upload', 'Upload image and click Analyze.', 'Result page should open with analysis details.', ''),
    ('WEB-018', 'Web history list shows scans', 'Open History after performing scan.', 'Scan history entries should display.', ''),
    ('WEB-019', 'Open history item on web', 'Click a history entry.', 'Result details page should appear.', ''),
    ('WEB-020', 'Chatbot send text question', 'Type question and press send.', 'Response should appear.', ''),
    ('WEB-021', 'Web chatbot suggestion click', 'Click suggested query chip.', 'Message should send and response appear.', ''),
    ('WEB-022', 'Web chatbot voice disabled safe mode', 'Click mic in browser if available.', 'Voice capture should start or show prompt.', ''),
    ('WEB-023', 'Play chatbot audio response', 'Click speaker icon after response.', 'Text-to-speech should play.', ''),
    ('WEB-024', 'Dashboard weather link works', 'Click weather quick action on dashboard.', 'Weather screen should open and display weather.', ''),
    ('WEB-025', 'Profile user data loads', 'Open Profile page.', 'User name, email, phone should load.', ''),
    ('WEB-026', 'Logout from web app', 'Click logout and confirm.', 'User should return to login page.', ''),
    ('WEB-027', 'Language selection works', 'Switch language to Hindi.', 'UI text should render in Hindi where available.', ''),
    ('WEB-028', 'Error shown for invalid login email', 'Enter malformed email on login.', 'Validation error should show.', ''),
    ('WEB-029', 'Error shown for short password', 'Enter short password and submit.', 'Validation message should show.', ''),
    ('WEB-030', 'Register success redirects home', 'Complete registration flow.', 'User should see home page after submit.', ''),
    ('WEB-031', 'Web signup shows OTP hint', 'Send OTP during registration.', 'Hint or notification should show OTP info.', ''),
    ('WEB-032', 'Profile edit fields available', 'Open profile editor from Profile page.', 'Phone and location edit fields should show.', ''),
    ('WEB-033', 'Browser back from result page', 'Press back after result page.', 'Web app should return to Scan page.', ''),
    ('WEB-034', 'History empty state visible', 'Open History with no entries.', 'Empty history message should display.', ''),
    ('WEB-035', 'Upload invalid file type blocked', 'Try uploading unsupported file type.', 'App should reject or show error.', ''),
    ('WEB-036', 'Session persists after refresh', 'Refresh browser on Home page.', 'User should still be logged in if session active.', ''),
    ('WEB-037', 'Web scanning tooltip visible', 'View Scan page tips section.', 'Camera guidance should display.', ''),
    ('WEB-038', 'Result page severity gauge visible', 'Open result page.', 'Severity gauge should show progress.', ''),
    ('WEB-039', 'Weather demo fallback on web', 'Open weather with invalid key.', 'Demo mode content should display.', ''),
    ('WEB-040', 'History item details show date', 'Open history page.', 'Each card should show date/time metadata.', ''),
    ('WEB-041', 'Chatbot suggestion list loads', 'Open AgroBot page.', 'Suggestion chips should render.', ''),
    ('WEB-042', 'Profile joined date displays', 'View Profile screen.', 'Joined date should display correctly.', ''),
    ('WEB-043', 'Update profile details', 'Change phone/location and save.', 'Profile should update on screen.', ''),
    ('WEB-044', 'Password field toggle is present', 'View login or register password field.', 'Visibility toggle should appear.', ''),
    ('WEB-045', 'Register invalid phone shows error', 'Type invalid phone number.', 'Validation should show on submit.', ''),
    ('WEB-046', 'Weather page shows icon and temperature', 'Open Weather page.', 'Weather icon and temp should display.', ''),
    ('WEB-047', 'Dashboard greet includes user name', 'Open dashboard.', 'Greeting includes the logged-in user name.', ''),
    ('WEB-048', 'Scan analysis progress indicator', 'Start analysis.', 'Loading indicator should show until done.', ''),
    ('WEB-049', 'Result actions are scrollable', 'Scroll result content.', 'Suggestion cards and text remain accessible.', ''),
    ('WEB-050', 'History list updates after refresh', 'Perform scan then refresh history page.', 'New record should still appear.', ''),
    ('WEB-051', 'Register page field labels visible', 'Open register page.', 'All field labels should be visible.', ''),
    ('WEB-052', 'Chatbot input placeholder visible', 'Open chatbot page.', 'Placeholder text should display.', ''),
    ('WEB-053', 'Profile main crops list shows items', 'View Profile.', 'Main crops should be visible.', ''),
    ('WEB-054', 'Analyze button disables while processing', 'Click Analyze and wait.', 'Button should show progress state.', ''),
    ('WEB-055', 'Register form validation summary', 'Submit invalid form.', 'Validation messages should appear near fields.', ''),
    ('WEB-056', 'Home page bottom nav responds on click', 'Click each navigation item.', 'Corresponding page should display.', ''),
    ('WEB-057', 'Web app handles missing network gracefully', 'Disconnect network then navigate.', 'UI should handle failure without crash.', ''),
    ('WEB-058', 'Chatbot response text readable', 'Send message.', 'Response text should be properly formatted.', ''),
    ('WEB-059', 'Result weather note content visible', 'Open result with weather data.', 'Weather note section should appear when present.', ''),
    ('WEB-060', 'Registration location autofill on web if available', 'Click location icon on register page.', 'Location should fill or show a fallback.', ''),
    ('WEB-061', 'Logout confirmation cancel on web', 'Click logout then cancel.', 'User remains logged in.', ''),
    ('WEB-062', 'Dashboard quick action labels visible', 'Open Dashboard.', 'Scan, AgroBot, History, Weather labels show.', ''),
    ('WEB-063', 'Scan page shows upload and camera buttons', 'View Scan.', 'Buttons appear and are clickable.', ''),
    ('WEB-064', 'Result page description section visible', 'Scroll through result page.', 'Description card should display.', ''),
    ('WEB-065', 'History detail page accessible from card', 'Click a history card.', 'Detail page loads.', ''),
    ('WEB-066', 'Profile logout button visible', 'View Profile.', 'Logout action button appears.', ''),
    ('WEB-067', 'Site title appears on login page', 'Open login page.', 'App title should appear in header.', ''),
    ('WEB-068', 'Forgot password link presence', 'Check login page.', 'If present, should show reset option or placeholder.', ''),
    ('WEB-069', 'Chatbot action button visible', 'View chat input area.', 'Send icon/button should be visible.', ''),
    ('WEB-070', 'Analyze page toggles crop selection', 'Open crop dropdown.', 'Correct crop options should appear.', ''),
    ('WEB-071', 'Weather quick action routes to weather screen', 'Click weather card.', 'Weather page should open.', ''),
    ('WEB-072', 'Register page OTP field appears after send', 'Send OTP.', 'OTP input field should become visible.', ''),
    ('WEB-073', 'Profile page updates after edit', 'Update info and save.', 'Changes should display on profile page.', ''),
    ('WEB-074', 'Login button disabled while loading', 'Click login and wait.', 'Button may show spinner and disable repeat clicks.', ''),
    ('WEB-075', 'History page empty state encourages scan', 'No history case.', 'Empty state should explain how to create scan history.', ''),
    ('WEB-076', 'Chatbot initial message is present', 'Open AgroBot page.', 'Bot welcome message should exist.', ''),
    ('WEB-077', 'Home nav remains on selected page', 'Switch between tabs.', 'Current tab stays selected.', ''),
    ('WEB-078', 'Register page privacy disclaimer visible', 'Scroll registration page.', 'Any privacy or hint text should be visible.', ''),
    ('WEB-079', 'App title in toolbar', 'Open web app and verify the toolbar title.', 'The app title should be visible at the top of the page.', ''),
    ('WEB-080', 'Autocomplete location field displays', 'Tap location icon if available.', 'Location field should autofill or show prompt.', ''),
    ('WEB-081', 'Result page shows severity gauge with percent', 'View result page.', 'Gauge should show percent value.', ''),
    ('WEB-082', 'History item includes crop type', 'Inspect history card.', 'Card should include crop or disease type.', ''),
    ('WEB-083', 'Weather page icon and temperature visible', 'Open weather page.', 'Icon and temperature should display.', ''),
    ('WEB-084', 'Scan page image preview updates after upload', 'Upload a valid image.', 'Preview container shows the image.', ''),
    ('WEB-085', 'Chatbot prompt responds after submit', 'Enter text and send.', 'Response should appear in chat.', ''),
    ('WEB-086', 'Dashboard content is visible after login', 'Login and open Dashboard.', 'Dashboard cards and greeting should show.', ''),
    ('WEB-087', 'Profile page displays user email', 'Open Profile.', 'User email should appear.', ''),
    ('WEB-088', 'Logout returns to login page', 'Confirm logout.', 'Login page should display.', ''),
    ('WEB-089', 'Register page handles invalid inputs gracefully', 'Submit invalid form.', 'Errors show and no navigation occurs.', ''),
    ('WEB-090', 'Weather overlay does not crash if API unavailable', 'Open weather with network down.', 'Error or fallback screen should appear.', ''),
    ('WEB-091', 'History card tap loads correct details', 'Click history item.', 'Result details page loads.', ''),
    ('WEB-092', 'Chatbot suggestion chips are clickable', 'Click chip.', 'Query should send.', ''),
    ('WEB-093', 'Profile edit sheet has save button', 'Open edit profile.', 'Save button should be available.', ''),
    ('WEB-094', 'Scan analysis page displays expected text', 'Open Scan page.', 'Guidance text should display.', ''),
    ('WEB-095', 'Register page email verification hint visible', 'Send OTP on register.', 'Hint should show OTP instructions.', ''),
    ('WEB-096', 'Web app supports dark mode if set', 'Toggle browser dark mode if supported.', 'UI should adapt if app does.', ''),
    ('WEB-097', 'Profile page main crops scroll horizontally if needed', 'Inspect crop list.', 'List should wrap or scroll.', ''),
    ('WEB-098', 'Chatbot page responds to tab reuse', 'Return to chat after using another tab.', 'Chat history persists.', ''),
    ('WEB-099', 'Logout confirmation appears before logout', 'Click logout action.', 'Confirmation dialog should appear.', ''),
    ('WEB-100', 'Dashboard quick action buttons are visible', 'View dashboard actions.', 'Scan, AgroBot, History, Weather buttons should appear.', ''),
]


def write_cases(filename, rows):
    with open(filename, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['id', 'title', 'description', 'steps', 'expected', 'result'])
        for row in rows:
            writer.writerow(row)


def main():
    write_cases('tests/test_cases_appium.csv', APP_CASES)
    write_cases('tests/test_cases_selenium.csv', WEB_CASES)
    print('Generated tests/test_cases_appium.csv and tests/test_cases_selenium.csv')


if __name__ == '__main__':
    main()
