// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3eWommYX_UF9PSdbGWOesILjUQiJeics',
    appId: '1:609970121261:web:d7033de3dc71ed767ce6a4',
    messagingSenderId: '609970121261',
    projectId: 'pdd-smart',
    authDomain: 'pdd-smart.firebaseapp.com',
    storageBucket: 'pdd-smart.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2S25f3Jkcruv6bYEUgaDDloUkRVWIz1I',
    appId: '1:609970121261:android:07e2f53eefec46bb7ce6a4',
    messagingSenderId: '609970121261',
    projectId: 'pdd-smart',
    storageBucket: 'pdd-smart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlPtsgbTWSMKy9oqcxS5uxaYweZK09kGQ',
    appId: '1:609970121261:ios:6bd89791b7f571be7ce6a4',
    messagingSenderId: '609970121261',
    projectId: 'pdd-smart',
    storageBucket: 'pdd-smart.firebasestorage.app',
    iosClientId: '609970121261-mdgfm2j0sar2cpuk5cehksavjv31h8av.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlPtsgbTWSMKy9oqcxS5uxaYweZK09kGQ',
    appId: '1:609970121261:ios:6bd89791b7f571be7ce6a4',
    messagingSenderId: '609970121261',
    projectId: 'pdd-smart',
    storageBucket: 'pdd-smart.firebasestorage.app',
    iosClientId: '609970121261-mdgfm2j0sar2cpuk5cehksavjv31h8av.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartcrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3eWommYX_UF9PSdbGWOesILjUQiJeics',
    appId: '1:609970121261:web:3da8b519ac13c74c7ce6a4',
    messagingSenderId: '609970121261',
    projectId: 'pdd-smart',
    authDomain: 'pdd-smart.firebaseapp.com',
    storageBucket: 'pdd-smart.firebasestorage.app',
  );
}
